apiVersion: v1
kind: Service
metadata:
  name: daily-status-service
  labels:
    app: daily-status
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: daily-status
